// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNCvk5nnkVKTONVDoWjbe0XGabpHX1OpU',
    appId: '1:443727921672:web:8a78b60a652c6586b507bd',
    messagingSenderId: '443727921672',
    projectId: 'haweel-503c7',
    authDomain: 'haweel-503c7.firebaseapp.com',
    databaseURL: 'https://haweel-503c7-default-rtdb.firebaseio.com',
    storageBucket: 'haweel-503c7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWCsAyrgTgiFIQQd2WwgR5_N-ail6v120',
    appId: '1:443727921672:android:0bd2dc36d93c72b7b507bd',
    messagingSenderId: '443727921672',
    projectId: 'haweel-503c7',
    databaseURL: 'https://haweel-503c7-default-rtdb.firebaseio.com',
    storageBucket: 'haweel-503c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfVZRL3ktTlTCJIsibjG-Br3aYLBo-Ozo',
    appId: '1:443727921672:ios:23815137973f0b59b507bd',
    messagingSenderId: '443727921672',
    projectId: 'haweel-503c7',
    databaseURL: 'https://haweel-503c7-default-rtdb.firebaseio.com',
    storageBucket: 'haweel-503c7.firebasestorage.app',
    iosClientId: '443727921672-j5fisvvmb34qmaq6ufiugurcg15aseg1.apps.googleusercontent.com',
    iosBundleId: 'com.example.haweel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfVZRL3ktTlTCJIsibjG-Br3aYLBo-Ozo',
    appId: '1:443727921672:ios:23815137973f0b59b507bd',
    messagingSenderId: '443727921672',
    projectId: 'haweel-503c7',
    databaseURL: 'https://haweel-503c7-default-rtdb.firebaseio.com',
    storageBucket: 'haweel-503c7.firebasestorage.app',
    iosClientId: '443727921672-j5fisvvmb34qmaq6ufiugurcg15aseg1.apps.googleusercontent.com',
    iosBundleId: 'com.example.haweel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNCvk5nnkVKTONVDoWjbe0XGabpHX1OpU',
    appId: '1:443727921672:web:bb83888983bddb7fb507bd',
    messagingSenderId: '443727921672',
    projectId: 'haweel-503c7',
    authDomain: 'haweel-503c7.firebaseapp.com',
    databaseURL: 'https://haweel-503c7-default-rtdb.firebaseio.com',
    storageBucket: 'haweel-503c7.firebasestorage.app',
  );

}